In [208]:
import pandas as pd

In [209]:
df = pd.read_csv("ai-impact-jobs-layoff-risk-dataset_messy.csv")

In [210]:
df.head()

   Age Education_Level  ...  AI_Training_Hours Layoff_Risk
0   59        Master's  ...               26.0        High
1   44        Master's  ...                9.0         Low
2   36      Bachelor's  ...                3.0         Low
3   27      Bachelor's  ...               26.0        High
4   49     High School  ...               19.0      Medium

[5 rows x 16 columns]

In [211]:
df.describe()

                Age  ...  AI_Training_Hours
count  20000.000000  ...       19970.000000
mean      40.361500  ...          12.610716
std       11.526333  ...          13.528054
min       21.000000  ...           0.000000
25%       30.000000  ...           4.000000
50%       40.000000  ...           8.000000
75%       50.000000  ...          18.000000
max       60.000000  ...          79.000000

[8 rows x 9 columns]

In [212]:
df["Industry"].unique()

array(['Finance', 'Manufacturing', 'Retail', 'Telecom', 'IT', 'Logistics',
       'Healthcare', 'Education', 'LOGISTICS', 'FINANCE', 'healthcare',
       ' IT ', ' Finance ', ' Telecom ', 'retail', 'HEALTHCARE',
       ' Retail ', 'manufacturing', 'logistics', ' Manufacturing ',
       ' Healthcare ', 'finance', ' Logistics ', 'it', 'TELECOM',
       'RETAIL', ' Education ', 'telecom', 'EDUCATION', 'MANUFACTURING',
       'education'], dtype=object)

In [213]:
df["Job_Role"].unique()

array(['Accountant', 'Production Supervisor', 'Store Manager', 'Auditor',
       'Network Engineer', 'Software Engineer', 'ML Engineer',
       'Inventory Analyst', 'Dispatcher', 'Health Analyst',
       'Support Specialist', 'Sales Associate', 'Academic Coordinator',
       'Financial Analyst', 'Operator', 'Research Assistant',
       'Quality Engineer', 'Teacher', 'Warehouse Manager',
       'Supply Chain Analyst', 'Operations Analyst', 'Medical Assistant',
       'Nurse', 'health analyst', 'Data Analyst', 'quality engineer',
       'ML ENGINEER', 'SOFTWARE ENGINEER', ' Warehouse Manager ',
       ' Dispatcher ', ' Academic Coordinator ', 'dispatcher',
       'NETWORK ENGINEER', 'SUPPORT SPECIALIST', 'INVENTORY ANALYST',
       'accountant', 'DATA ANALYST', ' ML Engineer ',
       ' Research Assistant ', ' Health Analyst ', ' Medical Assistant ',
       'operations analyst', ' Network Engineer ', 'RESEARCH ASSISTANT',
       'research assistant', 'production supervisor', 'OPERATOR',
       'QUALITY ENGINEER', 'SUPPLY CHAIN ANALYST', ' Teacher ',
       ' Data Analyst ', ' Inventory Analyst ', ' Operator ',
       'inventory analyst', 'OPERATIONS ANALYST', 'support specialist',
       'sales associate', ' Software Engineer ', 'AUDITOR',
       ' Quality Engineer ', 'supply chain analyst', ' Auditor ', 'nurse',
       'data analyst', ' Accountant '], dtype=object)

In [214]:
cat_cols = df.select_dtypes(include="object").columns.tolist()

In [215]:
for col in cat_cols:
    df[col] = df[col].str.lower().str.strip()

In [216]:
df["Industry"].unique()

array(['finance', 'manufacturing', 'retail', 'telecom', 'it', 'logistics',
       'healthcare', 'education'], dtype=object)

In [217]:
df["Job_Role"].unique()

array(['accountant', 'production supervisor', 'store manager', 'auditor',
       'network engineer', 'software engineer', 'ml engineer',
       'inventory analyst', 'dispatcher', 'health analyst',
       'support specialist', 'sales associate', 'academic coordinator',
       'financial analyst', 'operator', 'research assistant',
       'quality engineer', 'teacher', 'warehouse manager',
       'supply chain analyst', 'operations analyst', 'medical assistant',
       'nurse', 'data analyst'], dtype=object)

In [218]:
df["Layoff_Risk"].unique()

array(['high', 'low', 'medium'], dtype=object)

In [219]:
df["Layoff_Risk"] = df["Layoff_Risk"].str.upper().str.strip()

In [220]:
df = df.drop_duplicates()

In [221]:
X = df.drop(columns = 'Layoff_Risk', axis = 1 )
y = df["Layoff_Risk"]

In [222]:
X

       Age Education_Level  ...  Tasks_Automated_Percentage AI_Training_Hours
0       59        master's  ...                        40.0              26.0
1       44        master's  ...                        14.0               9.0
2       36      bachelor's  ...                         6.0               3.0
3       27      bachelor's  ...                        67.0              26.0
4       49     high school  ...                        26.0              19.0
...    ...             ...  ...                         ...               ...
19995   56      bachelor's  ...                        16.0               0.0
19996   43      bachelor's  ...                        77.0              67.0
19997   28     high school  ...                        55.0              10.0
19998   46      bachelor's  ...                        66.0               5.0
19999   36      bachelor's  ...                        30.0               8.0

[20000 rows x 15 columns]

In [223]:
y

0          HIGH
1           LOW
2           LOW
3          HIGH
4        MEDIUM
          ...
19995    MEDIUM
19996      HIGH
19997      HIGH
19998    MEDIUM
19999    MEDIUM
Name: Layoff_Risk, Length: 20000, dtype: object

In [224]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42, stratify= y)

In [225]:
X.isnull().sum()

Age                            0
Education_Level                0
Years_of_Experience           30
Industry                       0
Job_Role                       0
Company_Size                   0
Job_Level                      0
Routine_Task_Percentage        0
Creativity_Requirement         0
Human_Interaction_Level        0
AI_Adoption_Level              0
Number_of_AI_Tools_Used        0
AI_Usage_Hours_Per_Week       30
Tasks_Automated_Percentage    30
AI_Training_Hours             30
dtype: int64

In [226]:
columns_to_fill = ["Years_of_Experience" , "AI_Usage_Hours_Per_Week", "Tasks_Automated_Percentage" , "AI_Training_Hours" ]

for col in columns_to_fill:
    median_value = X_train[col].median()
    X_train[col] = X_train[col].fillna(median_value)
    X_test[col] = X_test[col].fillna(median_value)

In [227]:
X_train = pd.get_dummies(X_train, dtype=int)
X_test = pd.get_dummies(X_test, dtype=int)
X_train

       Age  ...  AI_Adoption_Level_medium
649     36  ...                         0
16457   59  ...                         0
4593    57  ...                         1
14506   56  ...                         0
6313    33  ...                         0
...    ...  ...                       ...
19693   30  ...                         0
2236    32  ...                         1
2632    59  ...                         0
4952    45  ...                         1
1304    56  ...                         1

[16000 rows x 54 columns]

In [228]:
X_test = X_test.reindex(columns=X_train.columns, fill_value=0)

In [229]:
num_cols = X.select_dtypes(include = "number").columns.tolist()

In [230]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()
X_train_scaled[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test_scaled[num_cols] = scaler.transform(X_test[num_cols])

In [231]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train_scaled, y_train)
lr_pred = lr_model.predict(X_test_scaled)
lr_accuracy = accuracy_score(y_test, lr_pred)
lr_classification_report = classification_report(y_test,lr_pred)
lr_confusion_matrix = confusion_matrix(y_test,lr_pred)
print(lr_accuracy)
print(lr_classification_report)
print(lr_confusion_matrix)

0.9375
              precision    recall  f1-score   support

        HIGH       0.95      0.96      0.96      1360
         LOW       0.95      0.95      0.95      1320
      MEDIUM       0.91      0.90      0.91      1320

    accuracy                           0.94      4000
   macro avg       0.94      0.94      0.94      4000
weighted avg       0.94      0.94      0.94      4000

[[1304    0   56]
 [   0 1252   68]
 [  63   63 1194]]

In [232]:
from sklearn.svm import SVC

svc_model = SVC(random_state=42)
svc_model.fit(X_train_scaled, y_train)
svc_pred = svc_model.predict(X_test_scaled)
svc_accuracy = accuracy_score(y_test, svc_pred)
svc_classification_report = classification_report(y_test,svc_pred)
svc_confusion_matrix = confusion_matrix(y_test,svc_pred)
print(svc_accuracy)
print(svc_classification_report)
print(svc_confusion_matrix)

0.946
              precision    recall  f1-score   support

        HIGH       0.96      0.96      0.96      1360
         LOW       0.96      0.95      0.96      1320
      MEDIUM       0.91      0.92      0.92      1320

    accuracy                           0.95      4000
   macro avg       0.95      0.95      0.95      4000
weighted avg       0.95      0.95      0.95      4000

[[1309    0   51]
 [   0 1255   65]
 [  53   47 1220]]

In [233]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_pred)
rf_classification_report = classification_report(y_test,rf_pred)
rf_confusion_matrix = confusion_matrix(y_test,rf_pred)
print(rf_accuracy)
print(rf_classification_report)
print(rf_confusion_matrix)

0.90825
              precision    recall  f1-score   support

        HIGH       0.93      0.94      0.93      1360
         LOW       0.94      0.93      0.93      1320
      MEDIUM       0.86      0.86      0.86      1320

    accuracy                           0.91      4000
   macro avg       0.91      0.91      0.91      4000
weighted avg       0.91      0.91      0.91      4000

[[1273    0   87]
 [   0 1223   97]
 [  99   84 1137]]

In [234]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)
dt_accuracy = accuracy_score(y_test, dt_pred)
dt_classification_report = classification_report(y_test,dt_pred)
dt_confusion_matrix = confusion_matrix(y_test,dt_pred)
print(dt_accuracy)
print(dt_classification_report)
print(dt_confusion_matrix)

0.83875
              precision    recall  f1-score   support

        HIGH       0.88      0.88      0.88      1360
         LOW       0.87      0.89      0.88      1320
      MEDIUM       0.76      0.74      0.75      1320

    accuracy                           0.84      4000
   macro avg       0.84      0.84      0.84      4000
weighted avg       0.84      0.84      0.84      4000

[[1200    1  159]
 [   0 1175  145]
 [ 168  172  980]]

In [ ]:
results = pd.DataFrame({
    "Model": ["Logistic Regression","SVC","Random Forest","Decision Tree"],
    "Accuracy": [lr_accuracy,svc_accuracy,rf_accuracy,dt_accuracy]
})

print(results.sort_values(by="Accuracy", ascending=False))

                 Model  Accuracy
1                  SVC   0.94600
0  Logistic Regression   0.93750
2        Random Forest   0.90825
3        Decision Tree   0.83875

In [240]:
import joblib
joblib.dump(svc_model,'svc_layoff.pkl')
joblib.dump(scaler,'layoff_scaler.pkl')
joblib.dump(X.columns.tolist(),'layoff_columns.pkl')

['layoff_columns.pkl']